# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]
  push:
    branches:
      - master    

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip wheel
        pip install setuptools twine telnetlib3
    - name: Run tests
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: coverage.xml
        path: /home/runner/work/telnet-commander/telnet-commander/test/coverage.xml
    - uses: actions/upload-artifact@v2
      with:
        name: htmlcov
        path: '/home/runner/work/telnet-commander/**/*htmlcov*'
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python ./pypi/setup.py sdist bdist_wheel
        twine upload dist/*
